apiVersion: sources.knative.dev/v1beta1
kind: SinkBinding
metadata:
  name: pubusb-currency-sink-bind
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: pubsub-currency
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: pubsub-client