apiVersion: sources.knative.dev/v1beta1
kind: SinkBinding
metadata:
  name: twitter-bind
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: twitter-producer
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: twitter-event-viewer