apiVersion: nats.io/v1alpha2
kind: NatsCluster
metadata:
  name: knative-nats-cluster-certs
spec:
  size: 3
  version: "1.3.0"

  tls:
    # Certificates to secure the NATS client connections:
    serverSecret: "nats-clients-tls"

    # Certificates to secure the routes.
    routesSecret: "nats-routes-tls"