apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: natss-sub-0
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: NatssChannel
    name: foo
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: natss-viewer