apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: natss-service-trigger
  namespace: default
spec:
  broker: natss-backed-broker
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: event-viewer