apiVersion: sources.knative.dev/v1alpha2
kind: SinkBinding
metadata:
  name: natss-currency-sink-bind
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: natss-currency
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: natss-client